### ISSUE TITLE
Git tags are missing

### ISSUE THREAD

**Issue by jeroennoten** [yireo-magento1/Yireo_EmailOverride#1]
It seems that this new git repository does not have any version tags. They may have been forgotten while migrating the repository.

**Comment by jissereitsma** [comment]
It never had git releases. It is strongly outdated and no longer maintained. I'm going to release 0.2.22 which is the last version that will appear. But it will be equal to installing `@dev`.

**Comment by jeroennoten** [comment]
Thanks @jissereitsma !

It indeed had no git **releases**, but the repository actually had git **tags** (which results in composer package versions). We have "^0.2.16" specified in our composer.json, which we cannot install anymore. Is there any possibility to restore those git tags so that running `composer install` works again?

**Comment by jissereitsma** [comment]
Unfortunately, no. The GitHub repository was moved from one account `yireo` to another `yireo-magento` and according to the docs this should have migrated all of the tags and everything as well. I'm not sure why this has not been migrated, but it is not something that can be fixed.

**Comment by jeroennoten** [comment]
Ok, no that's no big deal. As long as we have one version that we can install, that's fine.

However, the tag is not present at packagist, so it looks like something else is wrong. It may has to do with the GitLab webhook? https://packagist.org/packages/yireo/magento1-emailoverride

**Comment by jeroennoten** [comment]
The tag is in packagist now!

**Comment by jissereitsma** [comment]
:)
